module.exports= {
    name: 'App',
    children:[
        {
            name:'div',
            children:[{
                name:'Menu',
                children:[],
                nodeSvgShape:{
                    shapeProps:{
                        fill:'lightgreen'
                    }
                },
                tag:true,
                stats: {
                    state: true,
                    props: true,
                },
                value:true
            },
            {
                name:'h1',
                children:[],
                nodeSvgShape:{
                    shapeProps:{
                        fill:'lightgreen'
                    }
                },
                tag:true,
                stats:{
                    state:true,
                    props:true,
                },
                value:true
            },
        ]
        },
        {
            name:'Button',
            children:[{
                name:'h1',
                children:[],
                nodeSvgShape:{
                    shapeProps:{
                        fill:'lightgreen'
                    }
                },
                tag:true,
                stats:{
                    state:true,
                    props:true,
                },
                value:true
            },
            {
                name:'Target',
                children:[],
                nodeSvgShape:{
                    shapeProps:{
                        fill:'lightgreen'
                    }
                },
                tag:true,
                stats:{
                    state:true,
                    props:true,
                },
                value:true
            }
            ],
        nodeSvgShape:{
            shapeProps:{
                fill:'lightgreen'
            }
        },
        tag:true,
        stats:{
            state:true,
            props:true,
        },
        value:true
        }
    ],
    nodeSvgShape:{
        shapeProps:{
            fill:'lightgreen'
        }
    },
    tag:true,
    stats:{
        state:true,
        props:true,
    },
    value:true
}